"minecraft:story/mine_stone" : 1
"minecraft:story/upgrade_tools" : 2
"minecraft:story/smelt_iron" : 3
"minecraft:story/obtain_armor" : 4
"minecraft:story/lava_bucket" : 4
"minecraft:story/iron_tools" : 4
"minecraft:story/deflect_arrow" : 5
"minecraft:story/form_obsidian" : 5
"minecraft:story/mine_diamond" : 6
"minecraft:story/enter_the_nether" : 5
"minecraft:story/shiny_gear" : 6
"minecraft:story/enchant_item" : 7
"minecraft:story/cure_zombie_villager" : 64
"minecraft:story/follow_ender_eye" : 32
"minecraft:story/enter_the_end" : 8
"minecraft:nether/return_to_sender" : 48
"minecraft:nether/find_bastion" : 18
"minecraft:nether/obtain_ancient_debris" : 32
"minecraft:nether/fast_travel" : 0
"minecraft:nether/find_fortress" : 16
"minecraft:nether/obtain_crying_obsidian" : 10
"minecraft:nether/distract_piglin" : 12
"minecraft:nether/ride_strider" : 26
"minecraft:nether/uneasy_alliance" : 200
"minecraft:nether/loot_bastion" : 26
"minecraft:nether/use_lodestone" : 48
"minecraft:nether/netherite_armor" : 192
"minecraft:nether/get_wither_skull" : 48
"minecraft:nether/obtain_blaze_rod" : 12
"minecraft:nether/charge_respawn_anchor" : 32
"minecraft:nether/explore_nether" : 64
"minecraft:nether/summon_wither" : 128
"minecraft:nether/brew_potion" : 16
"minecraft:nether/create_beacon" : 192
"minecraft:nether/all_potions" : 128
"minecraft:nether/create_full_beacon" : 320
"minecraft:nether/all_effects" : 384
"minecraft:end/kill_dragon" : 92
"minecraft:end/dragon_egg" : 256
"minecraft:end/enter_end_gateway" : 24
"minecraft:end/respawn_dragon" : 128
"minecraft:end/dragon_breath" : 16
"minecraft:end/find_end_city" : 28
"minecraft:end/elytra" : 32
"minecraft:end/levitate" : 48
"minecraft:adventure/voluntary_exile" : 32
"minecraft:adventure/kill_a_mob" : 3
"minecraft:adventure/trade" : 10
"minecraft:adventure/honey_block_slide" : 32
"minecraft:adventure/ol_betsy" : 14
"minecraft:adventure/sleep_in_bed" : 6
"minecraft:adventure/hero_of_the_village" : 48
"minecraft:adventure/throw_trident" : 64
"minecraft:adventure/shoot_arrow" : 5
"minecraft:adventure/kill_all_mobs" : 192
"minecraft:adventure/totem_of_undying" : 64
"minecraft:adventure/summon_iron_golem" : 28
"minecraft:adventure/two_birds_one_arrow" : 48
"minecraft:adventure/whos_the_pillager_now" : 22
"minecraft:adventure/arbalistic" : 192
"minecraft:adventure/adventuring_time" : 300
"minecraft:adventure/very_very_frightening" : 92
"minecraft:adventure/sniper_duel" : 32
"minecraft:adventure/bullseye" : 32
"minecraft:husbandry/safely_harvest_honey" : 22
"minecraft:husbandry/breed_an_animal" : 12
"minecraft:husbandry/tame_an_animal" : 24
"minecraft:husbandry/fishy_business" : 16
"minecraft:husbandry/silk_touch_nest" : 32
"minecraft:husbandry/plant_seed" : 8
"minecraft:husbandry/bred_all_animals" : 192
"minecraft:husbandry/complete_catalogue" : 256
"minecraft:husbandry/tactical_fishing" : 20
"minecraft:husbandry/balanced_diet" : 256
"minecraft:husbandry/obtain_netherite_hoe" : 92